name: beldex_wallet
description: A Wallet for Beldex.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+21

# Version Code 1 Version Name 1.0.0 Release Date : 30-12-2021
# Version Code 2 Version Name 1.0.1 Release Date : 07-01-2022
# Version Code 3,4 Version Name 1.0.2 Internal Test Release Date : 02-02-2022
# Version Code 5 Version Name 1.0.3 Internal Test Release Date : 02-02-2022
# Version Code 5 Version Name 1.0.3 Production Release Date : 03-02-2022
# Version Code 6 Version Name 1.0.4 Production Release Date : 07-07-2022
# Version Code 7 Version Name 1.0.5 Production Release Date : 24-11-2022
# Version Code 8 Version Name 1.0.6 Production Release Date : 02-07-2023
# Version Code 9 Version Name 1.0.7 Production Release Date : 29-08-2023
# Version Code 10,11 Version Name 1.1.0 Production Release Date : 31-10-2023
# Version Code 12 Version Name 1.1.1 Internal Test Release Date : 25-01-2024
# Version Code 13 Version Name 1.2.0 Production Release Date : 30-01-2024
# Version Code 14 Version Name 1.3.0 Production Release Date : 22-02-2024
# Version Code 15 Version Name 1.3.0 Production Release Date : 27-02-2024
# Version Code 16 Version Name 1.3.2 Production Release Date : 29-02-2024
# Version Code 17 Version Name 1.3.3 Production Release Date : 19-03-2024
# Version Code 18 Version Name 1.4.0 Production Release Date : 22-04-2024
# Version Code 19 Version Name 1.4.1 Production Release Date : 30-07-2024
# Version Code 21 Version Name 2.0.0 Production Release Date : 30-08-2024

# keytool -genkey -v -keystore c:\Users\konst\key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.22.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #flutter_cupertino_localizations: ^1.0.1
  intl: any #^0.17.0
  url_launcher: ^6.0.20
  qr: ^2.0.0
  uuid: #^4.3.1
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.2
  rxdart: ^0.27.3
  yaml: ^3.1.0
  barcode_scan2: 4.3.0 # outdated and should be replaced
  http: ^1.1.0
  path_provider: ^2.0.9
  mobx: ^2.0.6
  flutter_mobx: ^2.0.4
  flutter_slidable: #^2.0.0
  share_plus: ^7.2.1
  # share: ^0.6.2+1
  #lottie:
  wakelock_plus: ^1.1.4
  toast: ^0.3.0
  #esys_flutter_share: ^1.0.2
  #date_range_picker: ^1.0.7
  custom_date_range_picker:
  dio: ^5.4.0
  #screen: ^0.0.5
  #floating_snackbar: any
  beldex_coin:
    path: ./beldex_coin
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  local_auth: ^2.1.0
  package_info_plus: ^4.2.0
  devicelocale: ^0.7.0
  auto_size_text: ^3.0.0
  synchronized: ^3.0.0
  flutter_html:
  delayed_consumer_hud:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.0
  basic_utils: ^5.7.0
  #win32: ^1.7.4+1
  draggable_scrollbar: ^0.1.0
  flutter_svg: ^2.0.9
  #flutter_launcher_icons: ^0.9.2
  #dropdown_search: ^0.4.9
  #wc_flutter_share: ^0.2.0 #new added 1.0.1 Date:10-01-2022
  #native_updater:
    #git: https://github.com/loadsmileau/native_updater #native_updater: ^0.1.1 #new added 1.0.1 Date:18-01-2022
  blurrycontainer: ^1.0.2
  connectivity_plus: ^5.0.2
  #flutter_windowmanager:
  font_awesome_flutter:
  upgrader:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  build_resolvers: ^2.0.6
  mobx_codegen: ^2.0.5+2
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  #pedantic: ^1.8.0
  lints: ^3.0.0


#flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/beldex_logo.png"
  ios: true
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/beldex_logo_foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true
  assets:
    - assets/images/new-images/
    - assets/images/
    - assets/images/new-images/ 
    - assets/node_list.yml
    - assets/testnet_node_list.yml
    - assets/changelog.yml
    - assets/text/
    - assets/faq/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Semibold.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans_regular.ttf
        - asset: assets/fonts/open_sans_medium.ttf
        - asset: assets/fonts/open_sans_medium.ttf
        - asset: assets/fonts/open_sans_semi_bold.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: false
#flutter_intl:
  #enabled: true # Required. Must be set to true to activate the package. Default: false
  #class_name: S # Optional. Sets the name for the generated localization class. Default: S
  #main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  #arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  #output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated