name: beldex_coin
version: 0.0.1

environment:
  sdk: ">=2.12.0 <4.0.0"
  #flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.beldex.coin
        pluginClass: BeldexCoinPlugin
      ios:
        pluginClass: BeldexCoinPlugin